# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
