# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source_link',
            old_name='imp',
            new_name='source',
        ),
    ]
