# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0002_auto_20161207_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='txt4',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
