# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0004_auto_20161209_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impoparcel_set', to='prop.Parcel'),
        ),
    ]
