# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 01:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0036_auto_20161208_1825'),
        ('impo', '0005_auto_20161209_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.CharField(db_index=True, max_length=50, null=True)),
                ('txt', models.CharField(db_index=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
            ],
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='IAddress',
        ),
        migrations.RenameModel(
            old_name='Parcel',
            new_name='IParcel',
        ),
        migrations.RenameModel(
            old_name='Policy',
            new_name='IPolicy',
        ),
        migrations.RenameModel(
            old_name='Property',
            new_name='IProperty',
        ),
        migrations.RenameModel(
            old_name='Value',
            new_name='IValue',
        ),
        migrations.RenameModel(
            old_name='Zone',
            new_name='IZone',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='parcel',
        ),
        migrations.AlterField(
            model_name='iaddress',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop.Parcel'),
        ),
        migrations.AlterField(
            model_name='iproperty',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop.Parcel'),
        ),
        migrations.AlterField(
            model_name='ivalue',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop.Property'),
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.AddField(
            model_name='ilot',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop.Lot'),
        ),
        migrations.AddField(
            model_name='ilot',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop.Parcel'),
        ),
    ]
