# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0006_auto_20161209_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='iparam',
            field=models.IntegerField(null=True),
        ),
    ]
