# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 18:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0008_auto_20161211_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaddress',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='iparcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
