# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0010_auto_20161214_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivalue',
            name='txt2',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
