# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0011_ivalue_txt2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipolicy',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='izone',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
