# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impo', '0012_auto_20161220_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipolicy',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ipolicy',
            name='num2',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ipolicy',
            name='num3',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='izone',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='izone',
            name='num2',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='izone',
            name='num3',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
