# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=50, null=True)),
                ('num', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('street_number', models.IntegerField(null=True)),
                ('street_prefix', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('street_type', models.CharField(max_length=20, null=True)),
                ('street_suffix', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Imp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('source_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=250)),
                ('update_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel', models.IntegerField(null=True)),
                ('txt', models.CharField(max_length=50, null=True)),
                ('num', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('street_number', models.IntegerField(null=True)),
                ('street_prefix', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('street_type', models.CharField(max_length=20, null=True)),
                ('street_suffix', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_col', models.CharField(max_length=50)),
                ('model_col', models.CharField(max_length=50)),
                ('imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Imp')),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel', models.IntegerField(null=True)),
                ('txt', models.CharField(max_length=50, null=True)),
                ('num', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Tie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.IntegerField(null=True)),
                ('valdate', models.CharField(max_length=50, null=True)),
                ('landval', models.IntegerField(null=True)),
                ('impval', models.IntegerField(null=True)),
                ('val', models.IntegerField(null=True)),
                ('txt', models.CharField(max_length=50, null=True)),
                ('num', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Muni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muni_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=50, null=True)),
                ('num', models.IntegerField(null=True)),
                ('depdate', models.DateField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Muni')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=50, null=True)),
                ('num', models.IntegerField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.Address')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Src',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('update_date', models.DateField(null=True)),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Muni')),
            ],
        ),
        migrations.CreateModel(
            name='Src_Imp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Imp')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Src')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valdate', models.DateField(null=True)),
                ('landval', models.IntegerField(null=True)),
                ('impval', models.IntegerField(null=True)),
                ('val', models.IntegerField(null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Property')),
            ],
        ),
        migrations.AddField(
            model_name='imp',
            name='muni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Muni'),
        ),
        migrations.AddField(
            model_name='address',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel'),
        ),
    ]
