# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0002_auto_20161108_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Src',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('update_date', models.DateField(null=True)),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Muni')),
            ],
        ),
        migrations.CreateModel(
            name='Src_Imp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Imp')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Src')),
            ],
        ),
    ]
