# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0003_src_src_imp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='street_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='street_suffix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='street_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='street_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='street_suffix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='street_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street_suffix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_suffix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
