# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0004_auto_20161108_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_address',
            name='postal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imp_address',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imp_parcel',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imp_property',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imp_tie',
            name='num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='imp_value',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='num',
            field=models.BigIntegerField(null=True),
        ),
    ]
