# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_auto_20161109_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_property',
            name='num2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='num3',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='txt2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imp_property',
            name='txt3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
