# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0008_auto_20161110_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_property',
            name='num2',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='imp_property',
            name='num3',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
