# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0010_auto_20161110_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_parcel',
            name='num2',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='num3',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='txt2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imp_parcel',
            name='txt3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
