# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0011_auto_20161110_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel_Ident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel')),
            ],
        ),
    ]
