# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0013_auto_20161114_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_tie',
            name='num2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imp_tie',
            name='txt2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
