# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0014_auto_20161115_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_tie',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
