# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0017_auto_20161116_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='agg',
        ),
        migrations.AddField(
            model_name='lot',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel'),
        ),
    ]
