# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0018_auto_20161116_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel_lot',
            name='num',
        ),
        migrations.AddField(
            model_name='parcel_lot',
            name='grp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel_lot',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.Lot'),
        ),
    ]
