# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0021_auto_20161117_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='txt',
            new_name='ext',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='txt',
            new_name='ext',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='num',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num',
        ),
        migrations.AddField(
            model_name='parcel',
            name='ext2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ext2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='valsrc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
