# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0022_auto_20161118_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_tie',
            name='grp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
