# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0024_auto_20161118_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot_Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.BigIntegerField(db_index=True, null=True)),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.Lot')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel')),
            ],
        ),
    ]
