# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0025_lot_parcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp_tie',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='imp_tie',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='parcel',
        ),
        migrations.AddField(
            model_name='parcel',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.Lot'),
        ),
        migrations.DeleteModel(
            name='Imp_Tie',
        ),
    ]
