# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0027_auto_20161119_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot_parcel',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='lot_parcel',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcel_lot',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='parcel_lot',
            name='parcel',
        ),
        migrations.DeleteModel(
            name='Lot_Parcel',
        ),
        migrations.DeleteModel(
            name='Parcel_Lot',
        ),
    ]
