# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0028_auto_20161119_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Muni')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('url', models.IntegerField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Policybound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=250, null=True)),
                ('fsr', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('uph', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('muni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Muni')),
            ],
        ),
        migrations.CreateModel(
            name='Zonebound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='zone',
            field=models.ManyToManyField(db_index=True, to='prop.Zone'),
        ),
        migrations.AddField(
            model_name='parcelzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Zone'),
        ),
        migrations.AddField(
            model_name='parcelpolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Policy'),
        ),
    ]
