# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0029_auto_20161121_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParcelPolicy',
            new_name='Parcel_Policy',
        ),
        migrations.RenameModel(
            old_name='ParcelZone',
            new_name='Parcel_Zone',
        ),
    ]
