# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0030_auto_20161121_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel_policy',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcel_policy',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='parcel_zone',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcel_zone',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Parcel_Policy',
        ),
        migrations.DeleteModel(
            name='Parcel_Zone',
        ),
    ]
