# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0032_parcel_policy_parcel_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='policy',
            field=models.ManyToManyField(through='prop.Parcel_Policy', to='prop.Policy'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='zone',
            field=models.ManyToManyField(through='prop.Parcel_Zone', to='prop.Zone'),
        ),
    ]
