# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0035_auto_20161207_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muni',
            old_name='muni_name',
            new_name='name',
        ),
    ]
