# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0037_auto_20161211_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp',
            name='muni',
        ),
        migrations.RemoveField(
            model_name='imp_address',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='imp_link',
            name='imp',
        ),
        migrations.RemoveField(
            model_name='imp_lot',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='imp_lot',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='imp_parcel',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='imp_property',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='imp_value',
            name='property',
        ),
        migrations.DeleteModel(
            name='Imp',
        ),
        migrations.DeleteModel(
            name='Imp_Address',
        ),
        migrations.DeleteModel(
            name='Imp_Link',
        ),
        migrations.DeleteModel(
            name='Imp_Lot',
        ),
        migrations.DeleteModel(
            name='Imp_Parcel',
        ),
        migrations.DeleteModel(
            name='Imp_Property',
        ),
        migrations.DeleteModel(
            name='Imp_Value',
        ),
    ]
