# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0039_auto_20161220_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='fsr',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='height',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='uph',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
